name: Sync Fork
on:
  schedule:
    - cron: "0 3 * * *"  # daily at 3 AM UTC
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          git remote add upstream https://github.com/ketjandr/nasa-spaceapps-project.git
          git fetch upstream
          git checkout main
          git merge upstream/main --allow-unrelated-histories || true
          git push origin main
